### ISSUE TITLE
Format Remark E Mail correctly

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/wc#10]
The mail content is not formatted.. Please change the following..
1.  Format the E Mail to look Professional .. At least what we see when we generate E Mail (in different lines) contents from Web Control Panel
2.  Change the Subject of E Mail from Remark Type to Remark Heading (Eg: Salary May 2015 ) for each Remarks added.  
3.  Test the modified code locally and then commit to SVN
4.  Consult Jithin for more details

**Comment by Revathyms** [comment]
I fix the issue by changing the Email Subject as Remark Heading. Format the Email to look Professional by using Table and br.
