### ISSUE TITLE
Employee Master:Joining Date and Leaving Date problem

### ISSUE THREAD

**Issue by ginualex** [thomastom99/wc#15]
Leaving Date should be grater than Joining Date
![joingdate](https://cloud.githubusercontent.com/assets/12725976/8448139/29b1c716-1fe1-11e5-84be-10f76939eaf7.jpg)

**Comment by thomastom99** [comment]
Leaving date should be optional as pointed by somebody..

**Comment by Revathyms** [comment]
Leaving Date is not a mandatory field. I check the code and remove the \* from the design to solve the issue. Now it's working fine.
