### ISSUE TITLE
Delete of multiple items doesn't work

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#18]
Application deletes only one menu item at a time from the selected menu items. Please find attached screenshots.
<img width="683" alt="screen shot_wc1" src="https://cloud.githubusercontent.com/assets/13657944/9104662/e64f9e40-3c2c-11e5-81f8-80b15d2a61ce.png">
<img width="687" alt="screen shot_wc2" src="https://cloud.githubusercontent.com/assets/13657944/9104666/efdf5c8e-3c2c-11e5-9e62-44964b9776e2.png">
<img width="693" alt="screen shot_wc3" src="https://cloud.githubusercontent.com/assets/13657944/9104668/f6b7a7a0-3c2c-11e5-9b54-f4c07293f295.png">

**Comment by thomastom99** [comment]
Please see whether this is easy to fix..

**Comment by Revathyms** [comment]
Do I have to implement multiple item delete option or do I have to show a message that only one item can delete at a time? Can you suggest me a solution?

**Comment by thomastom99** [comment]
Multiple Item deletion might be difficult as nested menus might be there.. So just say a warning like " Only One Menu can be deleted at a time.Please select only one menu.'

**Comment by Revathyms** [comment]
Actually the bug was does not showing any warning when deletes only one menu item at a time from the selected menu items. Now I fixed the bug by giving a warning.
