### ISSUE TITLE
Spelling mistakes found in Default Settings page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#23]
There are two spelling mistakes found in the Default Settings page. Please find attached screenshots.
<img width="800" alt="screen shot_default settings" src="https://cloud.githubusercontent.com/assets/13657944/9221695/e80947f4-4109-11e5-9f3f-7cfceaa792c3.png">
<img width="903" alt="screen shot 2015-default setting1" src="https://cloud.githubusercontent.com/assets/13657944/9221699/f0bd5282-4109-11e5-8f71-131ae83b0de1.png">

**Comment by Revathyms** [comment]
The bug is related to spelling mistake. Now I fix the bug by changing the spelling.
