### ISSUE TITLE
Spelling mistakes in the Manage Projects Settings Page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#24]
There are some spelling mistakes and an error in the "Please Note" message in the Manage Project Settings Page. Please find attached screenshots.
<img width="756" alt="screen shot 2015-08-13 at 2 54 51 pm" src="https://cloud.githubusercontent.com/assets/13657944/9247055/e8015d36-41cd-11e5-998a-67843ee153a9.png">
<img width="779" alt="screen shot 2015-08-13 at 10 42 40 am" src="https://cloud.githubusercontent.com/assets/13657944/9247064/f9ea2550-41cd-11e5-9c78-116e2b0c5b47.png">
<img width="901" alt="screen shot 2015-08-13 at 10 43 10 am" src="https://cloud.githubusercontent.com/assets/13657944/9247068/04016724-41ce-11e5-8cc6-39894c012f45.png">
<img width="865" alt="screen shot 2015-08-13 at 2 51 31 pm" src="https://cloud.githubusercontent.com/assets/13657944/9247104/339e0a00-41ce-11e5-8ff1-9e454aaab119.png">

**Comment by Revathyms** [comment]
Actually the bus was spelling mistake. now I fix the bug by changing the spelling.
