### ISSUE TITLE
Spelling mistakes in Employee Activity Reports Page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#25]
Spelling mistakes found in employee activity reports page. Please find attached screenshot.
<img width="851" alt="screen shot_employee work diary report" src="https://cloud.githubusercontent.com/assets/13657944/9322038/ccddfd72-458b-11e5-91a0-e14b3b25075a.png">

**Comment by Revathyms** [comment]
The bug was spelling mistake. Now fix the bug by changing the spelling dairy to diary.

**Comment by Revathyms** [comment]
The bug was spelling mistake. Now fix the bug by changing the spelling dairy to diary.
