### ISSUE TITLE
User is able to save Main Category Name without entering mandatory field Category Description.

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#26]
Application adds Main Category Name without showing error message for mandatory field "Category Description". Please find attached screenshot.
<img width="870" alt="screen shot_no error message" src="https://cloud.githubusercontent.com/assets/13657944/9323264/5ba89c64-459c-11e5-80b5-61a46e5b81b0.png">

**Comment by thomastom99** [comment]
Category Description should be Optional here not mandatory..

**Comment by Revathyms** [comment]
fix the bug by removing star from Category Description. Now the filed showing optional.
