### ISSUE TITLE
User is able to save Sub Category Name without entering mandatory field Sub Category Description.

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#27]
Application adds Sub Category Name without showing error message for mandatory field "Sub Category Description". Please find attached screenshot.
<img width="917" alt="screen shot 2015-08-18 at 11 29 56 am" src="https://cloud.githubusercontent.com/assets/13657944/9323373/bd087168-459d-11e5-9ef8-5f7c58aff2aa.png">

**Comment by thomastom99** [comment]
Remove the Mandatory Start from Sub Category Description

**Comment by Revathyms** [comment]
Fix the bug by removing star from Sub Category Description.
