### ISSUE TITLE
Spelling mistake in Manage Exam Candidates Page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#29]
Spelling mistake found in the error message of the Manage Exam Candidates page. Please find attached screenshot.
<img width="860" alt="screen shot 2015-08-18 at 12 23 30 pm" src="https://cloud.githubusercontent.com/assets/13657944/9324073/749ef18e-45a4-11e5-9d2c-9d5f355572d9.png">

**Comment by Revathyms** [comment]
Fix the bug by changing the spelling..
