### ISSUE TITLE
Spelling mistake in Manage Feedbacks page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#30]
Spelling mistake found in Manage Feedbacks page. Please find attached screenshot.
<img width="1242" alt="screen shot 2015-08-18 at 3 19 12 pm" src="https://cloud.githubusercontent.com/assets/13657944/9349638/5f6ec326-4666-11e5-8d9e-c25bf706a217.png">

**Comment by Revathyms** [comment]
Now I fixed the bug by changing the spelling Rane to Range
