### ISSUE TITLE
Spelling mistake in Dynamic Feedback Form Settings page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#31]
Spelling mistake in Dynamic Feedback Form Settings page. Please find attached screenshot.
<img width="1114" alt="screen shot_spelling" src="https://cloud.githubusercontent.com/assets/13657944/9349820/83c448a2-4668-11e5-9555-6aa8a552ff68.png">

**Comment by Revathyms** [comment]
The bug was spelling mistake. Now I fixed the bub by changing the spelling seprate to separate.
