### ISSUE TITLE
Spelling mistakes in Country Details page

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#32]
Spelling mistakes in Country Details page (Configure Web Pages-> Location Template Page Settings-> Country Master-> Country Details). Please find attached screenshot.
<img width="1021" alt="screen shot 2015-08-19 at 12 00 53 pm" src="https://cloud.githubusercontent.com/assets/13657944/9350192/1153465c-466c-11e5-823d-0e1346f0c973.png">

**Comment by Revathyms** [comment]
The bug was spelling mistake. Now I fixed the bug  by changing the speelling, detals-details, realated-related, applicaion-application.
