### ISSUE TITLE
Spelling mistakes in Enter State Details, City Details, Main Link, Sub Link Master Settings, Preview and Template Add-in Settings pages

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#33]
Spelling mistakes found in Enter State Details, City Details, Main Link, Sub Link Master Settings, Preview and Template Add-in Settings pages. Same mistakes are repeated in all the pages. Please find attached screenshot.
<img width="1196" alt="screen shot_spell" src="https://cloud.githubusercontent.com/assets/13657944/9350548/6b5dde0c-466f-11e5-9a3b-bb46ee103fb6.png">

**Comment by Revathyms** [comment]
The bug was spelling mistake. Now I fixed the bug by changing the speelling, detals-details, realated-related, applicaion-application.
