### ISSUE TITLE
Incorrect Help details in Country Details page.

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#34]
Incorrect Help details in Country Details page.The same mistake is repeated in Location Template Page Settings and Discussion Forum Page Template Settings. Please find attached screenshot.
<img width="1267" alt="screen shot_help details" src="https://cloud.githubusercontent.com/assets/13657944/9363803/24f61b4e-46c6-11e5-92c7-74da708a4080.png">

**Comment by Revathyms** [comment]
Actually the bug was incorrect help details in page. Now I fixed the bug by changing the help details.
