### ISSUE TITLE
Page title is same for Default settings, Forum Master, Topic Settings, Forum Default Settings.

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#39]
Page title is same for Default settings, Forum Master, Topic Settings, Forum Default Settings. Please find attached screenshots.
<img width="1098" alt="screen shot_heading1" src="https://cloud.githubusercontent.com/assets/13657944/9401978/d78f8630-47f4-11e5-9005-305197868f8a.png">
<img width="1048" alt="screen shot_default settings" src="https://cloud.githubusercontent.com/assets/13657944/9401982/ea5bfb04-47f4-11e5-9c47-0c945553cf3e.png">
<img width="1142" alt="screen shot_forum default settings" src="https://cloud.githubusercontent.com/assets/13657944/9401985/fa637ef0-47f4-11e5-8301-52c7bb5ce6ad.png">
<img width="1182" alt="screen shot_topic settings" src="https://cloud.githubusercontent.com/assets/13657944/9401991/0c548f50-47f5-11e5-8170-1cb7f8e320d5.png">

**Comment by thomastom99** [comment]
Please Put appropriate names..

**Comment by Revathyms** [comment]
The bug was Page title is same for multiple pages. Now I fixed the changes by giving appropriate names.
