### ISSUE TITLE
online exam candidate mail content error

### ISSUE THREAD

**Issue by ginualex** [thomastom99/wc#4]
1.heading: Time sheet(it is showing time sheet as heading )
2.footer link: there is no footer link
![u0-weu-d4-ec136b6e908effa82cb6fac4d8184719 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/12725976/7954792/43c88ad8-09f0-11e5-81a0-248dbc3607c0.jpg)

**Comment by thomastom99** [comment]
Please Discuss with Jithin and then Fix it. The Exam should have a Link.. I think Ginu didnt configured it correctly..

**Comment by thomastom99** [comment]
Mail Subject Heading needs to be changed ..

**Comment by Revathyms** [comment]
Online Exam Mail content Error Bug was having 2 issues. The First issue was Mail Subject Heading error. I fixed That Issue, by changing the mail Subject. The second issue was, Missing footer link. that was not actually a bug.

**Comment by thomastom99** [comment]
Is the link to Online exam is there now so that the user can directly go to the exam page?

**Comment by thomastom99** [comment]
Please consult Jithin Regarding the details fo exam link on the mail if needed..
