### ISSUE TITLE
Same page heading for multiple pages

### ISSUE THREAD

**Issue by Soorya2015** [thomastom99/wc#41]
Page title is same for E-Commerce Template Page Settings (Vendor Master, Product Category, Product Sub Category, E-Commerce Settings etc..). Please find attached screenshots.
<img width="1132" alt="screen shot_title" src="https://cloud.githubusercontent.com/assets/13657944/9655725/d80f6056-5250-11e5-8b75-1b72511d0ea5.png">
<img width="1101" alt="screen shot_title2" src="https://cloud.githubusercontent.com/assets/13657944/9655740/e77e9d68-5250-11e5-8566-40aa1711e363.png">
<img width="1153" alt="screen shot_title3" src="https://cloud.githubusercontent.com/assets/13657944/9655745/f1e1dbda-5250-11e5-9150-fc0923ae6d7d.png">

**Comment by Revathyms** [comment]
The bug was Page title is same for multiple pages. Now I fixed the changes by giving appropriate names.
