### ISSUE TITLE
Scenario 1- Taking the time sheet report

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/wc#52]
1.  Select time sheet report type, and a month (say January)
2.  Select a “from date”. (say 27, December 2015)
3.  Generate report
   This will generate a report with title like: 
   “Employee Time Sheet: ajith.joseph510@gmail.com Month : January Year : 2016”.
   But the report includes hours from selected date range. You may be noticed that he printer friendly report also having the same heading. There is no indication about selected date range
   It may better if 
   a.  It show the month name, iff dates are selected from one month itself.
   b.  Display the date range along with title of the report.

**Comment by Revathyms** [comment]
The bug was fixed. Now it display the month name, if dates are selected from one month itself. otherwise it display the date range.
