### ISSUE TITLE
From/To Date Range for February is wrong

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/wc#56]
When selecting From/To date range by selecting February form Employee activity report it shows to date as 29/01/2016

It should be 29/02/2016

Pl Correct..

There will be other mistakes similar to this.. Pl check..

**Comment by Revathyms** [comment]
The problem was related to the CalendarUserControlTo.SetDate(). "CalendarUserControlTo.SetDate("28/01/" + DateTime.Now.Year.ToString());", Here the month is set
 to 1. Now the bug was fixed by change the month
"CalendarUserControlTo.SetDate("28/02/" + DateTime.Now.Year.ToString());"
