### ISSUE TITLE
Navigation Error

### ISSUE THREAD

**Issue by Revathyms** [thomastom99/wc#7]
Navigation error on Question Bank Master page. On the Fresh Page(Without Filling any forms),When we click Add Question Button, control navigate
 to an error page...
![error add](https://cloud.githubusercontent.com/assets/8231745/7957050/2fea24c4-0a02-11e5-8117-1c009a00874f.png)

**Comment by thomastom99** [comment]
Validation checkk should be done for the fields before we need to proceed.. If the filed is blank , then display appropriate error message and stop. Error Message Filed should be there.. Please make sure that existing functionality should not be broken..This form is working for most of the direct cases.. so please be very careful.

**Comment by thomastom99** [comment]
Sachin .. Please work on this and other Online exam related Bugs..

**Comment by sachin-jose** [comment]
The issue happened when we click on the "Add questions" & "Edit Questions" button. I enclosed the code in try catch and set a warning. Now the problem is fixed and working fine now.
