### ISSUE TITLE
Add Remark Type Error

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/wc#9]
When we try to add Remark Type like Salary from EmployeeDetails/EDDefaultSettings.aspx It is showing error . Seems to be Database Table filed problem..

see the error
System.Data.OleDb.OleDbException: Data type mismatch in criteria expression. at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr) at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method) at System.Data.OleDb.OleDbCommand.ExecuteNonQuery() at DatabaseUtils.ExceuteQuery(String strQuery)

Please Discuss this with Jithin and then fix it..

**Comment by Revathyms** [comment]
The Issue was When we try to add Remark Type like Salary from EmployeeDetails/EDDefaultSettings.aspx It is showing error. Now I  fix the bug using alter table query
 ALTER TABLE EMP_DETAILS_REMARK_MASTER_TB
ALTER COLUMN RemarkName text
